machine:
  certSANs:
    - "prod-us-1.k8s.ilysium.io"
    - "talos-01.ilysium.internal"

  install:
    diskSelector:
      wwid: eui.e8238fa6bf530001001b448b4598d5be
    wipe: false

  nodeLabels: {}

  nodeAnnotations: {}
---
apiVersion: v1alpha1
kind: HostnameConfig
hostname: talos-01
auto: off
---
apiVersion: v1alpha1
kind: LinkConfig
name: eno1
mtu: 1500
up: true
addresses:
  - address: 10.20.20.20/27
routes:
  - gateway: 10.20.20.1
---
apiVersion: v1alpha1
kind: Layer2VIPConfig
name: 10.20.20.10
link: eno1
---
apiVersion: v1alpha1
kind: VolumeConfig
name: STATE
encryption:
  provider: luks2
  keys:
    - slot: 0
      tpm:
        options:
          pcrs: []
---
apiVersion: v1alpha1
kind: VolumeConfig
name: EPHEMERAL
encryption:
  provider: luks2
  keys:
    - slot: 0
      tpm:
        options:
          pcrs: []
---
apiVersion: v1alpha1
kind: UserVolumeConfig
name: longhorn-data
volumeType: partition
provisioning:
  diskSelector:
    match: disk.wwid == "naa.5002538870063fa6"
  maxSize: 900GiB
encryption:
  provider: luks2
  keys:
    - slot: 0
      tpm:
        options:
          pcrs: []
