machine:
  certSANs:
    - "prod-us-1.k8s.ilysium.io"
    - "talos-03.ilysium.internal"

  install:
    diskSelector:
      wwid: eui.002538bb41b3b1a4
    wipe: false

  nodeLabels:
    node.longhorn.io/create-default-disk: "config"

  nodeAnnotations:
    node.longhorn.io/default-disks-config: |
      [
        {
          "path": "/var/mnt/longhorn-data",
          "allowScheduling": true,
          "tags": ["ssd"]
        }
      ]
---
apiVersion: v1alpha1
kind: HostnameConfig
hostname: talos-03
auto: off
---
apiVersion: v1alpha1
kind: LinkConfig
name: eno1
mtu: 1500
up: true
addresses:
  - address: 10.20.20.18/27
routes:
  - gateway: 10.20.20.1
---
apiVersion: v1alpha1
kind: Layer2VIPConfig
name: 10.20.20.10
link: eno1
---
apiVersion: v1alpha1
kind: VolumeConfig
name: STATE
encryption:
  provider: luks2
  keys:
    - slot: 0
      tpm:
        options:
          pcrs: []
---
apiVersion: v1alpha1
kind: VolumeConfig
name: EPHEMERAL
encryption:
  provider: luks2
  keys:
    - slot: 0
      tpm:
        options:
          pcrs: []
---
apiVersion: v1alpha1
kind: UserVolumeConfig
name: longhorn-data
volumeType: partition
provisioning:
  diskSelector:
    match: disk.wwid == "naa.5002538e7031752e"
  minSize: 10GiB
  grow: true
encryption:
  provider: luks2
  keys:
    - slot: 0
      tpm:
        options:
          pcrs: []
